DROP TABLE IF EXISTS users
DROP TABLE IF EXISTS goals
DROP TABLE IF EXISTS nags

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email text UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE goals (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  user_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  start_date DATE,
  end_date DATE,
  cron VARCHAR(255)
);

CREATE TABLE nags (
  id SERIAL PRIMARY KEY NOT NULL,
  goal_id VARCHAR(255) NOT NULL REFERENCES goals(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  completion BOOLEAN,
  date DATE,
  time TIME
);